// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMbxAQe0c9GVfx6HmuU2Sllvzj0gyMlo',
    appId: '1:648922665058:web:28681e08ff248346c7013b',
    messagingSenderId: '648922665058',
    projectId: 'mygamemaster-62a1b',
    authDomain: 'mygamemaster-62a1b.firebaseapp.com',
    storageBucket: 'mygamemaster-62a1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-rBuG_B9pKIuKb0T2O_upl874X99I9Q',
    appId: '1:648922665058:android:82f56334b38e953fc7013b',
    messagingSenderId: '648922665058',
    projectId: 'mygamemaster-62a1b',
    storageBucket: 'mygamemaster-62a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTcdVrHBklirFQd40XaPl78_v73Qg4kI',
    appId: '1:648922665058:ios:5bc47737b2cbafb2c7013b',
    messagingSenderId: '648922665058',
    projectId: 'mygamemaster-62a1b',
    storageBucket: 'mygamemaster-62a1b.appspot.com',
    iosBundleId: 'com.example.mygamemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjTcdVrHBklirFQd40XaPl78_v73Qg4kI',
    appId: '1:648922665058:ios:5bc47737b2cbafb2c7013b',
    messagingSenderId: '648922665058',
    projectId: 'mygamemaster-62a1b',
    storageBucket: 'mygamemaster-62a1b.appspot.com',
    iosBundleId: 'com.example.mygamemaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIMbxAQe0c9GVfx6HmuU2Sllvzj0gyMlo',
    appId: '1:648922665058:web:a39c0255170a3477c7013b',
    messagingSenderId: '648922665058',
    projectId: 'mygamemaster-62a1b',
    authDomain: 'mygamemaster-62a1b.firebaseapp.com',
    storageBucket: 'mygamemaster-62a1b.appspot.com',
  );

}